import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    kotlin("jvm") version "2.2.21"
    // Kotlin classes are final by default, and Spring needs @Configuration and @Transactional classes
    // open to proxy them. This plugin opens exactly those.
    kotlin("plugin.spring") version "2.2.21"
    // Declared for `bootRun`. bootJar is turned off below, so the build's artifact stays a plain jar
    // like the Maven examples'.
    id("org.springframework.boot") version "4.0.7"
}

val southerVersion = "0.1.0-SNAPSHOT"
val raohVersion = "0.6.0"

java {
    // Built with the JDK the rest of the examples are built with, but everything this build emits
    // targets 21: that is Souther's runtime floor (souther-runtime and the generated classes target
    // it), so the Kotlin boundary asks no more of a JVM than the generated code it drives.
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
}

// === running the annotation processor ===
// A source set that exists only to run SoutherProcessor. javac will not process anything without at
// least one source, so it compiles the one package-info.java; the processor reads the module's .sou
// and emits the generated classes into this source set's output directory.
//
// This is what takes the place of the Maven build's plugin ordering. Gradle's Kotlin plugin compiles
// Kotlin *before* Java within a source set, which is the wrong way round here — everything on the
// Kotlin side depends on the generated bytecode and nothing on the Java side depends on Kotlin.
// Giving the processor a source set of its own takes it out of that ordering entirely: `main` simply
// depends on its output, and Gradle sequences the two compilations from that dependency.
val souther by sourceSets.creating {
    java.setSrcDirs(listOf("src/main/java"))
    resources.setSrcDirs(emptyList<String>())
}

// src/main/java belongs to that source set alone. It is `main`'s default Java directory too, and the
// package-info there carries an annotation, so javac emits a class file for it — from both
// compilations, which the jar then refuses as a duplicate entry. Nothing but the boundary's Kotlin is
// left in `main`.
sourceSets.main { java.setSrcDirs(emptyList<String>()) }

val southerSource: Directory = layout.projectDirectory.dir("src/main/souther")

tasks.named<JavaCompile>(souther.compileJavaTaskName) {
    options.compilerArgs.add("-Asouther.source=${southerSource.asFile.absolutePath}")
    // The .sou is not a javac source, so Gradle would not otherwise know this compilation reads it:
    // without declaring it, editing issues.sou leaves the task UP-TO-DATE and the previously
    // generated classes in place.
    inputs.dir(southerSource)
        .withPropertyName("southerSource")
        .withPathSensitivity(PathSensitivity.RELATIVE)
}

dependencies {
    // The generated classes. Declaring them as a dependency rather than by editing classpaths is what
    // orders compileSoutherJava before compileKotlin, and it reaches the test source set too, since
    // testImplementation extends implementation.
    implementation(souther.output)

    // souther-compiler is found on the processor path by ServiceLoader; souther-runtime is there
    // because the processor resolves the runtime types it emits references to.
    "southerAnnotationProcessor"("org.souther-lang:souther-compiler:$southerVersion")
    "southerAnnotationProcessor"("org.souther-lang:souther-runtime:$southerVersion")
    "southerImplementation"("org.souther-lang:souther-runtime:$southerVersion")
    "southerCompileOnly"("org.jspecify:jspecify:1.0.0")

    // The Souther generated code's runtime (decoder/encoder).
    implementation("org.souther-lang:souther-runtime:$southerVersion")
    implementation("net.unit8.raoh:raoh:$raohVersion")

    // reflect is what Spring reads constructor parameter names and nullability through. There is no
    // jackson-module-kotlin: no request or response shape is a Kotlin data class — every one of them
    // is a Souther data, decoded and encoded by the derived codec.
    implementation(kotlin("reflect"))

    // The boundary that actually runs: Boot's standard starters. DataSource / DSLContext /
    // TransactionManager and schema.sql execution are all left to autoconfig.
    implementation(platform(SpringBootPlugin.BOM_COORDINATES))
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-jooq")
    runtimeOnly("com.h2database:h2")

    testImplementation(platform(SpringBootPlugin.BOM_COORDINATES))
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_21
        // Read the JSR-305 nullability annotations Spring carries as strict Kotlin types rather than
        // platform types. Souther's own generated types say the same thing in JSpecify, which Kotlin
        // reads strictly on its own: souther-runtime marks its packages, and the module's package is
        // marked by the package-info under src/main/java.
        freeCompilerArgs.add("-Xjsr305=strict")
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 21
    options.encoding = "UTF-8"
}

tasks.test {
    useJUnitPlatform()
    testLogging { showStandardStreams = false }
}

// No repackage: the build's artifact is a plain jar, as the Maven examples' are. The generated classes
// live in another source set's output, so the jar has to be told to take them in.
tasks.bootJar { enabled = false }

tasks.jar {
    enabled = true
    archiveClassifier.set("")
    from(souther.output)
}
